### ISSUE TITLE
endif end if

### ISSUE THREAD

**Issue by billjwilliamson** [ellisonch/PostgreSQL-Stats-Aggregate#3]
Seems to require to be 
end if;

https://github.com/ellisonch/PostgreSQL-Stats-Aggregate/blob/575a28cb5049d077ca25619f0a6eec062943f511/pg_stats_aggregate.sql#L71

**Comment by ellisonch** [comment]
You're right.  Thanks!  Fixed in b34e5e0b6f32523a15567e7d737bb2d1ed63f7a4
